imgArray[0] = new Image();
imgArray[0].src = 'https://drive.google.com/uc?export=download&id=1Og6sNgkQSpQcLAsatUXaxUQ1LyUm0HmR';
imgArray[1] = new Image();
imgArray[1].src = 'https://drive.google.com/uc?export=download&id=1VGtBeP3FCRbBBm2RkBZc-bnOmSX2_BqB';
imgArray[2] = new Image();
imgArray[2].src = 'https://drive.google.com/uc?export=download&id=17rkmz4HcQH-SICqYsacvbRYdXYlRXCb2';
imgArray[3] = new Image();
imgArray[3].src = 'https://drive.google.com/uc?export=download&id=1shPHbnbzeZLb42hx_VO5tqnOxFcuSOOR';
imgArray[4] = new Image();
imgArray[4].src = 'https://drive.google.com/uc?export=download&id=1OmcBYd_USJPNbI5swTi3Zf9E68HSWjW-';
imgArray[5] = new Image();
imgArray[5].src = 'https://drive.google.com/uc?export=download&id=18N9uo6exLtNGtjJJxArZ36bQGEx29xRn';
imgArray[6] = new Image();
imgArray[6].src = 'https://drive.google.com/uc?export=download&id=14J5zYCdZeCuB0dqZKEIO5VXqDHYMMfnj';
imgArray[7] = new Image();
imgArray[7].src = 'https://drive.google.com/uc?export=download&id=1LDmzrusLy3z_ebtCvwQJi_99YfoIdSwi';
imgArray[8] = new Image();
imgArray[8].src = 'https://drive.google.com/uc?export=download&id=1RKSNAHafQEkem806N6cuoIrEjLR9fGUv';
imgArray[9] = new Image();
imgArray[9].src = 'https://drive.google.com/uc?export=download&id=1BBsaLSl4xRNzfngxL5xs_7WjgN_2Y-jx';
imgArray[10] = new Image();
imgArray[10].src = 'https://drive.google.com/uc?export=download&id=1gsVlG4Sr-7momxQNOSD8Gckry862Bfx2';
imgArray[11] = new Image();
imgArray[11].src = 'https://drive.google.com/uc?export=download&id=1FI1XfoMn4AxglA1UjoN6FxCq8xwRfSci';
imgArray[12] = new Image();
imgArray[12].src = 'https://drive.google.com/uc?export=download&id=13liWVAQ0iZ113Dw7pRkSEG_o8ThScIQE';